# Generated by Django 4.2.14 on 2024-08-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="is_active",
            new_name="active",
        ),
    ]
