# Generated by Django 4.2.14 on 2024-08-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderproduct_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderProduct",
        ),
    ]
