# Generated by Django 4.2.14 on 2024-09-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderaddress_order_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
