# Generated by Django 4.2.14 on 2024-08-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="product_images",
            name="product_name",
        ),
        migrations.AddField(
            model_name="product_images",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product_variant",
            ),
        ),
        migrations.AddField(
            model_name="product_variant",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="photos/thumbnail_images"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
