# Generated by Django 4.2.14 on 2024-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_variant",
            name="size",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
