# Generated by Django 4.2.14 on 2024-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_variant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
