# Generated by Django 4.2.14 on 2024-08-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_images_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product_variant'),
        ),
    ]
