# Generated by Django 4.2.14 on 2024-08-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_rename_reviewrating_reviewrating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="review",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="subject",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
