# Generated by Django 4.2.14 on 2024-08-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantoffer',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='productvariantoffer',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
