# Generated by Django 4.2.14 on 2024-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_remove_productvariantoffer_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantoffer",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
