# Generated by Django 4.2.14 on 2024-08-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_productvariantoffer_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantoffer',
            name='discount_percent',
        ),
    ]
